version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:14.17
    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

  test:
    docker:
      - image: circleci/node:14.17
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      - run: yarn install
      - run: yarn test     # test
      - run: yarn coverage:codacy # check coverage
      - run: yarn lint     # lint

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
